name: libphonenumber_plugin
description: Flutter package for Google libphonenumber, for Android and Web. Uses Flutter Federated Package for interoperability.
version: 0.3.1
homepage: https://github.com/natintosh/plugin_libphonenumber.git

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  libphonenumber_platform_interface:
    git:
      url: git@github.com:sakchhams/plugin_libphonenumber.git
      path: libphonenumber_platform_interface

  libphonenumber_web:
    git:
      url: git@github.com:sakchhams/plugin_libphonenumber.git
      path: libphonenumber_web

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/libphonenumber_plugin/js/libphonenumber.js
    - packages/libphonenumber_plugin/js/stringbuffer.js
    - assets/js/libphonenumber.js
    - assets/js/stringbuffer.js

  plugin:
    platforms:
      android:
        package: com.example.libphonenumber_plugin
        pluginClass: LibphonenumberPlugin
      ios:
        pluginClass: FLTLibphonenumberPlugin
      web:
        default_package: libphonenumber_web
